#!/usr/bin/env python3
"""
doc2html.py — Universal DOC/DOCX to HTML Converter
====================================================
Converts Microsoft Word documents (.doc and .docx) into self-contained HTML
files with embedded styles and base64-encoded images.

Usage:
    python doc2html.py document.docx
    python doc2html.py document.doc output.html
    python doc2html.py --help

Converter priority:
    .docx  →  mammoth  (best fidelity for modern Word files)
    .doc   →  pypandoc / Pandoc  →  LibreOffice  →  Word COM (Windows only)
             →  doc→docx upgrade via win32com or LibreOffice, then mammoth

NOTE: mammoth is a ZIP-based (.docx) parser and CANNOT read binary .doc files
      directly.  A dedicated .doc converter is always required for that format.

Author : Anh Vinh (generated by Claude)
License: MIT
"""

from __future__ import annotations

import argparse
import base64
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


# ---------------------------------------------------------------------------
# ANSI colour helpers (disabled automatically on Windows without ANSI support)
# ---------------------------------------------------------------------------

def _supports_colour() -> bool:
    return hasattr(sys.stdout, "isatty") and sys.stdout.isatty()


_COLOUR = _supports_colour()

def _c(code: str, text: str) -> str:
    return f"\033[{code}m{text}\033[0m" if _COLOUR else text

def info(msg: str)    -> None: print(_c("36", f"[INFO]  {msg}"))
def ok(msg: str)      -> None: print(_c("32", f"[OK]    {msg}"))
def warn(msg: str)    -> None: print(_c("33", f"[WARN]  {msg}"), file=sys.stderr)
def error(msg: str)   -> None: print(_c("31", f"[ERROR] {msg}"), file=sys.stderr)
def step(msg: str)    -> None: print(_c("35", f"  →  {msg}"))


# ---------------------------------------------------------------------------
# CSS injected into every HTML output
# ---------------------------------------------------------------------------

BASE_CSS = """
/* ── doc2html.py base stylesheet ── */
*, *::before, *::after { box-sizing: border-box; }

body {
    font-family: "Calibri", "Segoe UI", Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.5;
    color: #222;
    background: #fff;
    max-width: 860px;
    margin: 2em auto;
    padding: 0 1.5em 4em;
}

/* Headings */
h1, h2, h3, h4, h5, h6 {
    font-family: "Calibri Light", "Segoe UI Light", Arial, sans-serif;
    color: #1a1a2e;
    margin-top: 1.4em;
    margin-bottom: 0.3em;
    line-height: 1.25;
}
h1 { font-size: 2em;   border-bottom: 2px solid #4472c4; padding-bottom: .25em; }
h2 { font-size: 1.5em; border-bottom: 1px solid #c0c0c0; padding-bottom: .2em; }
h3 { font-size: 1.2em; }
h4 { font-size: 1.05em; font-style: italic; }

/* Paragraphs */
p  { margin: 0 0 0.6em; }

/* Lists */
ul, ol { margin: 0.4em 0 0.8em 1.8em; padding: 0; }
li      { margin-bottom: 0.25em; }

/* Tables */
table {
    border-collapse: collapse;
    width: 100%;
    margin: 1em 0;
    font-size: 0.97em;
}
th, td {
    border: 1px solid #bbb;
    padding: 6px 10px;
    text-align: left;
    vertical-align: top;
}
th {
    background: #4472c4;
    color: #fff;
    font-weight: 600;
}
tr:nth-child(even) td { background: #f4f7fb; }

/* Inline text decorations */
strong, b { font-weight: 700; }
em, i     { font-style: italic; }
u         { text-decoration: underline; }
s, strike { text-decoration: line-through; }
code, pre {
    font-family: "Consolas", "Courier New", monospace;
    background: #f4f4f4;
    border-radius: 3px;
}
code { padding: 1px 4px; font-size: 0.9em; }
pre  { padding: 0.8em 1em; overflow-x: auto; border: 1px solid #ddd; }

/* Images */
img {
    max-width: 100%;
    height: auto;
    display: block;
    margin: 0.6em 0;
}

/* Horizontal rule */
hr { border: none; border-top: 1px solid #ccc; margin: 1.5em 0; }

/* Links */
a { color: #1155cc; }
a:hover { color: #0b3d91; }
""".strip()


# ---------------------------------------------------------------------------
# Dependency checks
# ---------------------------------------------------------------------------

def check_dependencies() -> dict[str, bool]:
    """
    Probe for every optional dependency and return a status dict.
    Does NOT raise; callers decide what to do with missing tools.
    """
    status: dict[str, bool] = {}

    # Python package: mammoth
    try:
        import mammoth  # noqa: F401
        status["mammoth"] = True
    except ImportError:
        status["mammoth"] = False

    # Python package: pypandoc
    try:
        import pypandoc  # noqa: F401
        status["pypandoc"] = True
    except ImportError:
        status["pypandoc"] = False

    # System binary: pandoc
    status["pandoc"] = shutil.which("pandoc") is not None

    # System binary: libreoffice (soffice)
    status["libreoffice"] = (
        shutil.which("soffice") is not None
        or shutil.which("libreoffice") is not None
    )

    # Windows COM automation (pywin32)
    try:
        import win32com.client  # noqa: F401
        status["win32com"] = True
    except ImportError:
        status["win32com"] = False

    return status


def _print_dep_summary(deps: dict[str, bool]) -> None:
    info("Dependency check:")
    labels = {
        "mammoth":    "mammoth (Python pkg)",
        "pypandoc":   "pypandoc (Python pkg)",
        "pandoc":     "Pandoc (system binary)",
        "libreoffice":"LibreOffice (system binary)",
        "win32com":   "pywin32 / Word COM (Windows only)",
    }
    for key, label in labels.items():
        symbol = "✓" if deps.get(key) else "✗"
        colour = "32" if deps.get(key) else "90"
        print(f"    {_c(colour, symbol)}  {label}")


# ---------------------------------------------------------------------------
# HTML helpers
# ---------------------------------------------------------------------------

def _wrap_html(title: str, body_html: str, extra_css: str = "") -> str:
    """Wrap a fragment in a complete, standalone HTML5 document."""
    combined_css = BASE_CSS + ("\n\n" + extra_css if extra_css else "")
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "<head>\n"
        '  <meta charset="UTF-8" />\n'
        '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
        f"  <title>{_escape_html(title)}</title>\n"
        "  <style>\n"
        + "\n".join("    " + line for line in combined_css.splitlines())
        + "\n  </style>\n"
        "</head>\n"
        "<body>\n"
        + body_html
        + "\n</body>\n"
        "</html>\n"
    )


def _escape_html(text: str) -> str:
    return (
        text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
    )


def _embed_images_as_base64(html: str, base_dir: Path) -> str:
    """
    Replace <img src="relative/path"> with inline base64 data URIs so the
    HTML file is truly self-contained.
    """
    MIME = {
        ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
        ".gif": "image/gif", ".bmp": "image/bmp", ".svg": "image/svg+xml",
        ".webp": "image/webp",
    }

    def replacer(m: re.Match) -> str:
        prefix, src, suffix = m.group(1), m.group(2), m.group(3)
        # Skip already-embedded or remote images
        if src.startswith("data:") or src.startswith("http"):
            return m.group(0)
        img_path = (base_dir / src).resolve()
        if not img_path.exists():
            warn(f"Image not found, skipping embed: {img_path}")
            return m.group(0)
        ext = img_path.suffix.lower()
        mime = MIME.get(ext, "application/octet-stream")
        b64 = base64.b64encode(img_path.read_bytes()).decode()
        return f'{prefix}data:{mime};base64,{b64}{suffix}'

    # Match both single- and double-quoted src attributes
    pattern = r'(<img\s[^>]*src=")([^"]+)(")'
    html = re.sub(pattern, replacer, html, flags=re.IGNORECASE)
    pattern2 = r"(<img\s[^>]*src=')([^']+)(')"
    html = re.sub(pattern2, replacer, html, flags=re.IGNORECASE)
    return html


# ---------------------------------------------------------------------------
# Converter: mammoth  (.docx → HTML)
# ---------------------------------------------------------------------------

#: Custom style map passed to mammoth.
#: Format: "Word style name" => "HTML element"
MAMMOTH_STYLE_MAP = """
p[style-name='Heading 1'] => h1:fresh
p[style-name='Heading 2'] => h2:fresh
p[style-name='Heading 3'] => h3:fresh
p[style-name='Heading 4'] => h4:fresh
p[style-name='Heading 5'] => h5:fresh
p[style-name='Heading 6'] => h6:fresh
p[style-name='Title']     => h1.document-title:fresh
p[style-name='Subtitle']  => p.subtitle:fresh
p[style-name='Quote']     => blockquote:fresh
p[style-name='Intense Quote'] => blockquote.intense:fresh
p[style-name='Caption']   => p.caption:fresh
p[style-name='List Paragraph'] => li:fresh
r[style-name='Strong']    => strong
r[style-name='Emphasis']  => em
r[style-name='Intense Emphasis'] => em.intense
r[style-name='Code']      => code
""".strip()

MAMMOTH_EXTRA_CSS = """
/* Mammoth-specific extras */
.document-title { font-size: 2.4em; font-weight: 800; margin-bottom: .1em; }
.subtitle        { font-size: 1.2em; color: #555; margin-top: -.5em; }
blockquote {
    border-left: 4px solid #4472c4;
    margin: 1em 0 1em 1em;
    padding: 0.5em 1em;
    color: #444;
    font-style: italic;
    background: #f8f9fc;
}
blockquote.intense { border-color: #c0392b; background: #fff8f7; }
.caption { font-size: 0.88em; color: #666; font-style: italic; }
""".strip()


def _mammoth_embed_image(image) -> dict:
    """
    Callback for mammoth's convert_image hook.

    mammoth passes an image object whose .open() method is a context manager
    (returns a contextlib.closing-wrapped file).  We must use 'with' to read
    the bytes safely — calling .open().read() directly fails because the
    'closing' wrapper has no .read() attribute.
    """
    with image.open() as img_file:
        data = img_file.read()
    b64 = base64.b64encode(data).decode()
    return {"src": f"data:{image.content_type};base64,{b64}"}


def convert_docx_mammoth(input_path: Path, output_path: Path) -> None:
    """
    Convert a .docx file to a standalone HTML file using the mammoth library.

    mammoth is purpose-built for Word→HTML and handles:
      • Headings, bold, italic, underline, strikethrough
      • Tables (including merged cells via rowspan/colspan)
      • Lists (nested)
      • Hyperlinks
      • Images (embedded as base64 automatically by mammoth)
      • Custom style mappings via style_map

    Args:
        input_path:  Path to the source .docx file.
        output_path: Path where the .html file should be written.

    Raises:
        ImportError:   if mammoth is not installed.
        FileNotFoundError: if the input file does not exist.
        RuntimeError:  if mammoth reports conversion errors.
    """
    try:
        import mammoth
    except ImportError:
        raise ImportError(
            "mammoth is required for .docx conversion.\n"
            "Install it with:  pip install mammoth"
        )

    step(f"Converting '{input_path.name}' using mammoth …")

    with input_path.open("rb") as fh:
        result = mammoth.convert_to_html(
            fh,
            style_map=MAMMOTH_STYLE_MAP,
            # Embed images as base64 data URIs (no external files needed)
            convert_image=mammoth.images.img_element(_mammoth_embed_image),
        )

    # Report any warnings mammoth emitted (e.g. unsupported features)
    for msg in result.messages:
        if "error" in str(msg.type).lower():
            warn(f"mammoth: {msg.message}")
        else:
            step(f"mammoth note: {msg.message}")

    body_html = result.value
    title = input_path.stem
    full_html = _wrap_html(title, body_html, MAMMOTH_EXTRA_CSS)

    output_path.write_text(full_html, encoding="utf-8")
    ok(f"Saved → {output_path}")


# ---------------------------------------------------------------------------
# Helper: upgrade a legacy .doc → .docx  (so mammoth can then read it)
# ---------------------------------------------------------------------------

def upgrade_doc_to_docx(doc_path: Path, tmp_dir: Path) -> Path:
    """
    Convert a legacy binary .doc file to .docx format so that mammoth (which
    is a ZIP/OOXML parser) can process it.

    Why this is necessary
    ---------------------
    The legacy .doc format is a binary OLE Compound File.  mammoth only
    understands OOXML (.docx, which is a ZIP archive).  Passing a .doc file
    to mammoth raises ``zipfile.BadZipFile`` immediately.  This function
    bridges that gap by re-saving the document as .docx using whichever
    tool is available on the current machine.

    Conversion strategies (tried in order)
    ---------------------------------------
    1. **Word COM** (Windows + Microsoft Word installed)
       Opens the file with ``win32com.client`` and calls ``SaveAs2`` with
       ``wdFormatXMLDocument`` (format code 12), which writes a proper .docx.

    2. **LibreOffice headless**
       Calls ``soffice --headless --convert-to docx`` which uses LibreOffice's
       built-in Word filter for the re-save.

    Args:
        doc_path: Absolute path to the source .doc file.
        tmp_dir:  A temporary directory where the .docx will be written.

    Returns:
        Path to the newly created .docx file inside *tmp_dir*.

    Raises:
        RuntimeError: if neither Word COM nor LibreOffice is available, or if
                      the conversion subprocess/COM call fails.
    """
    docx_path = tmp_dir / (doc_path.stem + ".docx")

    # ── Strategy 1: Word COM ─────────────────────────────────────────────────
    try:
        import win32com.client as win32
        step("Upgrading .doc → .docx via Microsoft Word COM …")
        word = None
        try:
            word = win32.gencache.EnsureDispatch("Word.Application")
            word.Visible = False
            word.DisplayAlerts = False
            doc = word.Documents.Open(str(doc_path.resolve()))
            WD_FORMAT_XML_DOCUMENT = 12   # .docx
            doc.SaveAs2(str(docx_path.resolve()), FileFormat=WD_FORMAT_XML_DOCUMENT)
            doc.Close(False)
            ok(f"Upgraded → {docx_path.name}")
            return docx_path
        finally:
            if word is not None:
                try:
                    word.Quit()
                except Exception:
                    pass
    except ImportError:
        pass  # pywin32 not installed, try next strategy

    # ── Strategy 2: LibreOffice headless ────────────────────────────────────
    soffice = shutil.which("soffice") or shutil.which("libreoffice")
    if soffice:
        step("Upgrading .doc → .docx via LibreOffice …")
        # Copy input into tmp_dir first (LibreOffice writes output next to source)
        tmp_doc = tmp_dir / doc_path.name
        shutil.copy2(doc_path, tmp_doc)
        cmd = [soffice, "--headless", "--convert-to", "docx", "--outdir",
               str(tmp_dir), str(tmp_doc)]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        if result.returncode != 0:
            raise RuntimeError(
                f"LibreOffice .doc→.docx upgrade failed (exit {result.returncode}).\n"
                f"stderr: {result.stderr}"
            )
        candidates = list(tmp_dir.glob("*.docx"))
        if not candidates:
            raise RuntimeError("LibreOffice ran but produced no .docx file.")
        ok(f"Upgraded → {candidates[0].name}")
        return candidates[0]

    # ── No strategy available ────────────────────────────────────────────────
    raise RuntimeError(
        "Cannot convert legacy .doc file: no suitable converter found.\n\n"
        "To fix this on Windows, install ONE of the following:\n\n"
        "  Option A – Pandoc (recommended, free, no Office required):\n"
        "    winget install --id JohnMacFarlane.Pandoc\n"
        "    or download from: https://pandoc.org/installing.html\n"
        "    then re-run:  pip install pypandoc\n\n"
        "  Option B – LibreOffice (free, no Office required):\n"
        "    winget install --id TheDocumentFoundation.LibreOffice\n"
        "    or download from: https://www.libreoffice.org/download/\n\n"
        "  Option C – pywin32 (requires Microsoft Word to be installed):\n"
        "    pip install pywin32\n\n"
        "After installing, re-run the script — no code changes needed."
    )


# ---------------------------------------------------------------------------
# Converter: pypandoc / Pandoc  (.doc or .docx → HTML)
# ---------------------------------------------------------------------------

def convert_doc_pandoc(input_path: Path, output_path: Path) -> None:
    """
    Convert a Word document (.doc or .docx) to HTML using pypandoc / Pandoc.

    Pandoc is a universal document converter that understands both legacy
    .doc (via LibreOffice filter internally) and modern .docx.  Using
    --standalone produces a complete HTML file; --embed-resources embeds
    all images as base64 (Pandoc ≥ 2.19 replaces --self-contained).

    Args:
        input_path:  Path to the source .doc or .docx file.
        output_path: Path where the .html file should be written.

    Raises:
        ImportError:   if pypandoc is not installed.
        RuntimeError:  if Pandoc binary is not found or conversion fails.
    """
    try:
        import pypandoc
    except ImportError:
        raise ImportError(
            "pypandoc is required for .doc conversion.\n"
            "Install it with:  pip install pypandoc\n"
            "Then install Pandoc: https://pandoc.org/installing.html"
        )

    step(f"Converting '{input_path.name}' using Pandoc …")

    # Build extra args; try --embed-resources (Pandoc ≥2.19) with fallback
    # to the older --self-contained flag.
    def _run(embed_flag: str) -> str:
        return pypandoc.convert_file(
            str(input_path),
            "html5",
            outputfile=None,           # return as string
            extra_args=[
                "--standalone",
                embed_flag,
                "--metadata", f"title={input_path.stem}",
                "--highlight-style=tango",
            ],
        )

    try:
        raw_html = _run("--embed-resources")
    except Exception:
        step("--embed-resources not supported, retrying with --self-contained …")
        try:
            raw_html = _run("--self-contained")
        except Exception as exc:
            raise RuntimeError(
                f"Pandoc conversion failed: {exc}\n"
                "Make sure Pandoc ≥ 2.11 is installed: https://pandoc.org/installing.html"
            ) from exc

    # Inject our own CSS before Pandoc's closing </style> tag (or <body>)
    injection = f"\n<style>\n{BASE_CSS}\n</style>\n"
    if "</head>" in raw_html:
        raw_html = raw_html.replace("</head>", injection + "</head>", 1)
    else:
        raw_html = injection + raw_html

    output_path.write_text(raw_html, encoding="utf-8")
    ok(f"Saved → {output_path}")


# ---------------------------------------------------------------------------
# Converter: LibreOffice  (.doc/.docx → HTML)
# ---------------------------------------------------------------------------

def convert_via_libreoffice(input_path: Path, output_path: Path) -> None:
    """
    Convert a Word document to HTML using LibreOffice in headless mode.

    LibreOffice is called as a subprocess with the --headless flag so no
    GUI window ever appears.  It writes the HTML alongside the source file
    in a temp directory, after which we move it to the desired output path.

    LibreOffice binary name differs per platform:
        Linux/macOS: soffice  or  libreoffice
        Windows:     "C:\\Program Files\\LibreOffice\\program\\soffice.exe"
                     (added to PATH by the installer on most systems)

    Args:
        input_path:  Path to the source document.
        output_path: Desired path for the resulting .html file.

    Raises:
        RuntimeError: if LibreOffice is not found or conversion fails.
    """
    soffice = shutil.which("soffice") or shutil.which("libreoffice")
    if soffice is None:
        raise RuntimeError(
            "LibreOffice not found on PATH.\n"
            "Install from: https://www.libreoffice.org/download/download/\n"
            "On Ubuntu/Debian:  sudo apt install libreoffice\n"
            "On macOS (Homebrew): brew install --cask libreoffice"
        )

    step(f"Converting '{input_path.name}' using LibreOffice …")

    # LibreOffice writes output next to the source file, so we use a temp dir.
    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp_input = Path(tmp_dir) / input_path.name
        # Copy input into temp dir (LibreOffice may lock the original)
        shutil.copy2(input_path, tmp_input)

        cmd = [
            soffice,
            "--headless",
            "--convert-to", "html:HTML",
            "--outdir", tmp_dir,
            str(tmp_input),
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)

        if result.returncode != 0:
            raise RuntimeError(
                f"LibreOffice returned exit code {result.returncode}.\n"
                f"stdout: {result.stdout}\nstderr: {result.stderr}"
            )

        # Find the generated HTML file
        generated = list(Path(tmp_dir).glob("*.html"))
        if not generated:
            raise RuntimeError(
                "LibreOffice ran but produced no .html output.\n"
                f"stdout: {result.stdout}\nstderr: {result.stderr}"
            )

        lo_html = generated[0].read_text(encoding="utf-8", errors="replace")

        # Embed any <img> tags that point to local files LibreOffice created
        lo_html = _embed_images_as_base64(lo_html, Path(tmp_dir))

        # Inject base CSS
        injection = f"\n<style>\n{BASE_CSS}\n</style>\n"
        if "</head>" in lo_html:
            lo_html = lo_html.replace("</head>", injection + "</head>", 1)
        else:
            lo_html = injection + lo_html

    output_path.write_text(lo_html, encoding="utf-8")
    ok(f"Saved → {output_path}")


# ---------------------------------------------------------------------------
# Converter: Microsoft Word COM automation (Windows only)
# ---------------------------------------------------------------------------

def convert_via_word_com(input_path: Path, output_path: Path) -> None:
    """
    Convert a Word document to HTML via Word's COM automation (Windows only).

    This approach launches Microsoft Word invisibly and uses its built-in
    "Save As HTML" export, producing the highest-fidelity output at the cost
    of requiring a licensed Microsoft Word installation.

    Uses wdFormatHTML (8) for compatibility or wdFormatFilteredHTML (10) for
    a cleaner, lighter-weight output.

    Args:
        input_path:  Absolute path to the source document.
        output_path: Desired path for the resulting .html file.

    Raises:
        ImportError:   if pywin32 is not installed.
        RuntimeError:  if Word cannot be launched or conversion fails.
    """
    try:
        import win32com.client as win32
    except ImportError:
        raise ImportError(
            "pywin32 is required for Word COM conversion.\n"
            "Install it with:  pip install pywin32"
        )

    step(f"Converting '{input_path.name}' using Microsoft Word COM …")

    word = None
    doc  = None
    try:
        word = win32.gencache.EnsureDispatch("Word.Application")
        word.Visible = False
        word.DisplayAlerts = False

        doc = word.Documents.Open(str(input_path.resolve()))

        # wdFormatFilteredHTML = 10  (cleaner HTML, recommended)
        # wdFormatHTML         = 8   (preserves more Word-specific markup)
        WD_FORMAT_FILTERED_HTML = 10
        doc.SaveAs2(str(output_path.resolve()), FileFormat=WD_FORMAT_FILTERED_HTML)
        doc.Close(False)

        # Word writes supporting images into a folder beside the HTML;
        # re-read the HTML and inline those images as base64.
        html = output_path.read_text(encoding="utf-8", errors="replace")
        html = _embed_images_as_base64(html, output_path.parent)

        # Inject base CSS
        injection = f"\n<style>\n{BASE_CSS}\n</style>\n"
        if "</head>" in html:
            html = html.replace("</head>", injection + "</head>", 1)
        html_path = output_path.with_suffix(".html")
        html_path.write_text(html, encoding="utf-8")

    except Exception as exc:
        raise RuntimeError(f"Word COM conversion failed: {exc}") from exc
    finally:
        # Always quit Word to avoid ghost processes
        if word is not None:
            try:
                word.Quit()
            except Exception:
                pass

    ok(f"Saved → {output_path}")


# ---------------------------------------------------------------------------
# Main dispatcher
# ---------------------------------------------------------------------------

def convert_to_html(
    input_path: str | Path,
    output_path: str | Path | None = None,
    *,
    prefer_pandoc: bool = False,
) -> Path:
    """
    Main entry point: convert *input_path* to an HTML file.

    Automatically chooses the best available converter:
      .docx  →  mammoth  (unless prefer_pandoc=True and Pandoc is available)
      .doc   →  pypandoc → LibreOffice → Word COM (Windows)

    Args:
        input_path:    Path to the Word document (.doc or .docx).
        output_path:   Optional desired output path.  If None, the output
                       is placed beside the input with a .html extension.
        prefer_pandoc: If True, use Pandoc even for .docx files (useful
                       when you want Pandoc's richer metadata handling).

    Returns:
        The Path of the generated HTML file.

    Raises:
        FileNotFoundError: if the input file does not exist.
        ValueError:        if the file extension is not .doc or .docx.
        RuntimeError:      if no suitable converter is found.
    """
    input_path = Path(input_path).resolve()

    # ── Validate input ──────────────────────────────────────────────────────
    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")

    ext = input_path.suffix.lower()
    if ext not in (".doc", ".docx"):
        raise ValueError(
            f"Unsupported file extension '{ext}'. "
            "Only .doc and .docx are accepted."
        )

    # ── Resolve output path ─────────────────────────────────────────────────
    if output_path is None:
        output_path = input_path.with_suffix(".html")
    else:
        output_path = Path(output_path).resolve()
        # Ensure the target directory exists
        output_path.parent.mkdir(parents=True, exist_ok=True)

    info(f"Input  : {input_path}")
    info(f"Output : {output_path}")

    deps = check_dependencies()
    _print_dep_summary(deps)
    print()

    # ── .docx branch ────────────────────────────────────────────────────────
    if ext == ".docx":
        if not prefer_pandoc and deps["mammoth"]:
            info("Strategy: mammoth (native Python, .docx)")
            convert_docx_mammoth(input_path, output_path)

        elif deps["pypandoc"] and deps["pandoc"]:
            info("Strategy: Pandoc via pypandoc (.docx)")
            convert_doc_pandoc(input_path, output_path)

        elif deps["libreoffice"]:
            info("Strategy: LibreOffice headless (.docx)")
            convert_via_libreoffice(input_path, output_path)

        elif deps["win32com"]:
            info("Strategy: Microsoft Word COM (.docx)")
            convert_via_word_com(input_path, output_path)

        else:
            raise RuntimeError(
                "No converter found for .docx files!\n\n"
                "Install at least one of:\n"
                "  pip install mammoth            # recommended\n"
                "  pip install pypandoc           # + Pandoc binary\n"
                "  sudo apt install libreoffice   # Linux\n"
                "  brew install --cask libreoffice  # macOS"
            )

    # ── .doc branch ─────────────────────────────────────────────────────────
    else:  # ext == ".doc"
        if deps["pypandoc"] and deps["pandoc"]:
            info("Strategy: Pandoc via pypandoc (.doc)")
            convert_doc_pandoc(input_path, output_path)

        elif deps["libreoffice"]:
            info("Strategy: LibreOffice headless (.doc)")
            convert_via_libreoffice(input_path, output_path)

        elif deps["win32com"]:
            info("Strategy: Microsoft Word COM (.doc)")
            convert_via_word_com(input_path, output_path)

        elif deps["mammoth"]:
            # mammoth cannot read binary .doc directly (it is an OLE file,
            # not a ZIP).  However we can upgrade .doc → .docx first using
            # Word COM or LibreOffice, then feed the .docx to mammoth.
            info("Strategy: upgrade .doc → .docx, then mammoth")
            with tempfile.TemporaryDirectory() as tmp:
                docx_path = upgrade_doc_to_docx(input_path, Path(tmp))
                convert_docx_mammoth(docx_path, output_path)

        else:
            raise RuntimeError(
                "No converter found for .doc files!\n\n"
                "To fix this on Windows, install ONE of the following:\n\n"
                "  Option A – Pandoc (recommended, free, no Office required):\n"
                "    winget install --id JohnMacFarlane.Pandoc\n"
                "    or download from: https://pandoc.org/installing.html\n"
                "    then re-run:  pip install pypandoc\n\n"
                "  Option B – LibreOffice (free, no Office required):\n"
                "    winget install --id TheDocumentFoundation.LibreOffice\n"
                "    or download from: https://www.libreoffice.org/download/\n\n"
                "  Option C – pywin32 (requires Microsoft Word to be installed):\n"
                "    pip install pywin32\n\n"
                "After installing, re-run the script — no code changes needed."
            )

    return output_path


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="doc2html",
        description=(
            "Universal DOC/DOCX → HTML converter.\n"
            "Supports mammoth, Pandoc, LibreOffice, and Word COM (Windows)."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python doc2html.py report.docx\n"
            "  python doc2html.py report.docx output.html\n"
            "  python doc2html.py legacy.doc --prefer-pandoc\n"
            "  python doc2html.py --check-deps\n"
        ),
    )
    parser.add_argument(
        "input",
        nargs="?",
        help="Path to the input .doc or .docx file.",
    )
    parser.add_argument(
        "output",
        nargs="?",
        default=None,
        help="Optional path for the output .html file (default: same dir as input).",
    )
    parser.add_argument(
        "--prefer-pandoc",
        action="store_true",
        default=False,
        help="Use Pandoc instead of mammoth even for .docx files.",
    )
    parser.add_argument(
        "--check-deps",
        action="store_true",
        default=False,
        help="Print dependency status and exit.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """
    Parse CLI arguments and run the conversion.

    Returns:
        0 on success, 1 on error.
    """
    parser = _build_parser()
    args   = parser.parse_args(argv)

    # ── --check-deps mode ───────────────────────────────────────────────────
    if args.check_deps:
        deps = check_dependencies()
        _print_dep_summary(deps)
        return 0

    # ── Normal conversion mode ──────────────────────────────────────────────
    if not args.input:
        parser.print_help()
        return 1

    try:
        result = convert_to_html(
            args.input,
            args.output,
            prefer_pandoc=args.prefer_pandoc,
        )
        print()
        ok(f"Conversion complete!  Open in browser: {result}")
        return 0

    except FileNotFoundError as exc:
        error(str(exc))
        return 1

    except ValueError as exc:
        error(str(exc))
        return 1

    except ImportError as exc:
        error(str(exc))
        return 1

    except RuntimeError as exc:
        error(str(exc))
        return 1

    except KeyboardInterrupt:
        print()
        warn("Interrupted by user.")
        return 130


if __name__ == "__main__":
    sys.exit(main())
